# version: '3.7'

# services:
#   user-project:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     # restart: always
#     command: uvicorn main:app --workers 1 --host 0.0.0.0
#     volumes:
#       - .:/app
#     ports:
#       - 8003:8000
#     env_file:
#       - .env
#     depends_on:
#       - postgres_db

#   postgres_db:
#     image: postgres:latest
#     container_name: PostgresCont
#     # restart: always
#     environment:
#       - POSTGRES_USER=shrey
#       - POSTGRES_PASSWORD=Sonu619
#       - POSTGRES_DB=Ecommerce
#     ports:
#       - '5431:5431'
#     volumes:
#       - postgres_db:/var/lib/postgresql/data
#     command: >
#       sh -c "sleep 10 && psql -h localhost -U shrey -d postgres -c 'CREATE DATABASE Ecommerce'"

# volumes:
#   postgres_db:
#     driver: local
